backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

media_folder: "static/image/theme" # Where to store images
public_folder: "/image/theme" # The src attribute for uploaded media will begin with this

collections:
  - name: "posts" # Used in routes, e.g., /admin/collections/blog
    label: "Posts" # Used in the UI
    folder: "content/post" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template
    fields: # The fields for each document, usually in front matter
      - {label: "Title", name: "title", widget: "string", default: "untitled"}
      - {label: "Date", name: "date", widget: "datetime"}
      - {label: "Draft", name: "draft", widget: "boolean", default: true}
      - {label: "Image Path", name: "image", widget: "string", default: "/image/theme/og.png"}
      - {label: "Body", name: "body", widget: "markdown"}

  - name: "unpublished" # Used in routes, e.g., /admin/collections/blog
    label: "Unpublished" # Used in the UI
    folder: "content/unpublished" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template
    fields: # The fields for each document, usually in front matter
      - {label: "Title", name: "title", widget: "string", default: "untitled"}
      - {label: "Date", name: "date", widget: "datetime"}
      - {label: "Draft", name: "draft", widget: "boolean", default: true}
      - {label: "Image Path", name: "image", widget: "string", default: "/image/theme/og.png"}
      - {label: "Body", name: "body", widget: "markdown"}
